### PR TITLE
Fix dark mode navigation bar

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Update gradle wrapper

### 2nd commit
- Methodize a few things in ForegroundService

###  3rd commit
- Correct some theming duplicates
- Made navigation bar dark for dark mode

### CODE REVIEW

**Comment by mueller-ma** [comment]
Can you post screenshots? Previous vs after this PR.

**Comment by TacoTheDank** [comment]
> Can you post screenshots? Previous vs after this PR.

image

**Comment by mueller-ma** [comment]
> Update gradle wrapper

How did you update the wrapper script?

> Methodize a few things in ForegroundService

IMO it's fine as it currently is, so I don't think I'll merge this commit.

> Made navigation bar dark for dark mode

Actually it is dark on my device running Android 10. Seems that I have to have a closer look at this.

**Comment by TacoTheDank** [comment]
> > Update gradle wrapper
> 
> How did you update the wrapper script?
With git bash.

> 
> > Methodize a few things in ForegroundService
> 
> IMO it's fine as it currently is, so I don't think I'll merge this commit.
Alright.

> 
> > Made navigation bar dark for dark mode
> 
> Actually it is dark on my device running Android 10. Seems that I have to have a closer look at this.
Well ok then.

**Comment by mueller-ma** [comment]
Sorry for letting you wait. On api 22 the navigation bar is currently black and with this PR it changes to white. However the icons are also white:
grafik


AFAIK the nav bar icon color cannot be changed on api 22.

I made some improvements that are working on a AOSP api 30. Can you check the latest master on your device?

**Comment by TacoTheDank** [comment]
@mueller-ma Sure. I use the versions built by F-Droid, so I'll wait for it to be built.

**Comment by TacoTheDank** [comment]
@mueller-ma Installed. It now works as shown in the screenshot above. Thanks!

**Pull request closed without merging**
